### ISSUE TITLE
Error on index.html on `bb sync`

### ISSUE THREAD

**Issue by mistermark** [GewenBB/bb-cli-mosaic-widget#1]
The index.html needs to have the following Doctype header:

`<!DOCTYPE html>`

The HTML tag needs to have namespace definitions:

`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" xmlns:g="http://www.backbase.com/2008/gadget">`

**Comment by GewenBB** [comment]
https://github.com/GewenBB/bb-cli-mosaic-widget/commit/e30f83649db182cfb66e46b19472cbdabdae8462
